{
 "title": "E-Commerce Observability",
 "description": "ENPM818P Group 10 - E-Commerce Observability using Grafana and Prometheus",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "HTTP 5xx Error Rate – users-service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 *\r\nsum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      service=\"users-service\",\r\n      status=~\"5..\"\r\n    }[5m]\r\n  )\r\n)\r\n/\r\nsum(\r\n  rate(\r\n    http_server_requests_seconds_count{\r\n      service=\"users-service\"\r\n    }[5m]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Memory Usage – shop",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  container_memory_working_set_bytes{namespace=\"shop\", container!=\"\"}\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage per pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(\r\n  container_memory_working_set_bytes{namespace=\"shop\", image!=\"\"}\r\n) by (pod)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(kube_pod_container_status_restarts_total{namespace=\"shop\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 latency per route (URI) for users-service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (uri, le) (\r\n    rate(\r\n      http_server_requests_seconds_bucket{\r\n        namespace=\"shop\",\r\n        service=\"users-service\"\r\n      }[5m]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage – shop",
   "type": "timeseries",
   "description": "This shows CPU for each website pod (storefront, products, etc.).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_cpu_usage_seconds_total{namespace=\"shop\", container!=\"\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 latency for the whole users-service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le) (\r\n    rate(\r\n      http_server_requests_seconds_bucket{\r\n        namespace=\"shop\",\r\n        service=\"users-service\"\r\n      }[5m]\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic (bytes/s) – shop pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by (pod) (\r\n  rate(container_network_receive_bytes_total{namespace=\"shop\"}[5m])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}