AWSTemplateFormatVersion: '2010-09-09'
Description: IRSA Role for Kubernetes Cluster Autoscaler on EKS

Parameters:

  ClusterName:
    Type: String
    Default: ecommerce-eks-cluster

  OIDCProviderArn:
    Type: String
    Description: "Full ARN of the OIDC Provider"

  OIDCProviderId:
    Type: String
    Description: "OIDC Provider ID"


Resources:
  # IAM Policy for Cluster Autoscaler
  ClusterAutoscalerPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${ClusterName}-cluster-autoscaler-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - autoscaling:DescribeAutoScalingGroups
              - autoscaling:DescribeAutoScalingInstances
              - autoscaling:DescribeLaunchConfigurations
              - autoscaling:DescribeScalingActivities
              - autoscaling:DescribeTags
              - autoscaling:DescribeLaunchTemplates
              - autoscaling:DescribeScheduledActions
              - autoscaling:SetDesiredCapacity
              - autoscaling:UpdateAutoScalingGroup
              - autoscaling:TerminateInstanceInAutoScalingGroup
              - autoscaling:CreateOrUpdateTags
            Resource: "*"

          - Effect: Allow
            Action:
              - ec2:DescribeLaunchTemplateVersions
            Resource: "*"

          - Effect: Allow
            Action:
              - iam:CreateServiceLinkedRole
            Resource: "*"
            Condition:
              StringEquals:
                iam:AWSServiceName: autoscaling.amazonaws.com

  # Cluster Autoscaler IRSA Role
  ClusterAutoscalerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ClusterName}-cluster-autoscaler-irsa-role"
      AssumeRolePolicyDocument:
        Fn::Sub: >
          {
            "Version": "2012-10-17",
            "Statement": [
              {
                "Effect": "Allow",
                "Principal": {
                  "Federated": "${OIDCProviderArn}"
                },
                "Action": "sts:AssumeRoleWithWebIdentity",
                "Condition": {
                  "StringEquals": {
                    "oidc.eks.${AWS::Region}.amazonaws.com/id/${OIDCProviderId}:sub":
                      "system:serviceaccount:kube-system:cluster-autoscaler",
                    "oidc.eks.${AWS::Region}.amazonaws.com/id/${OIDCProviderId}:aud":
                      "sts.amazonaws.com"
                  }
                }
              }
            ]
          }
      ManagedPolicyArns:
        - !Ref ClusterAutoscalerPolicy


Outputs:

  ClusterAutoscalerRoleArn:
    Description: "IAM Role ARN for Cluster Autoscaler"
    Value: !GetAtt ClusterAutoscalerRole.Arn
    Export:
      Name: ClusterAutoscalerRoleArn
