AWSTemplateFormatVersion: '2010-09-09'
Description: IRSA Role for EBS CSI Driver

Parameters:
  ClusterName:
    Type: String
    Default: ecommerce-eks-cluster

  OIDCProviderArn:
    Type: String

  OIDCProviderId:
    Type: String

Resources:
  EBSCsiPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: !Sub "${ClusterName}-ebs-csi-policy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - ec2:AttachVolume
              - ec2:DetachVolume
              - ec2:CreateVolume
              - ec2:DeleteVolume
              - ec2:DescribeInstances
              - ec2:DescribeVolumes
              - ec2:DescribeSnapshots
              - ec2:CreateTags
              - ec2:DeleteTags
            Resource: "*"

  EBSCsiRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ClusterName}-ebs-csi-irsa-role"
      AssumeRolePolicyDocument:
        Fn::Sub:
          - |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Federated": "${OidcArn}"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                    "StringEquals": {
                      "oidc.eks.${AWS::Region}.amazonaws.com/id/${OidcId}:sub": "system:serviceaccount:kube-system:ebs-csi-controller-sa"
                    }
                  }
                }
              ]
            }
          - { OidcArn: !Ref OIDCProviderArn, OidcId: !Ref OIDCProviderId }
      ManagedPolicyArns:
        - !Ref EBSCsiPolicy

Outputs:
  EBSCsiRoleArn:
    Value: !GetAtt EBSCsiRole.Arn
    Export:
      Name: EBSCsiRoleArn
