AWSTemplateFormatVersion: '2010-09-09'
Description: Corrected EKS Cluster for E-Commerce Microservices Platform (OIDC removed).

Parameters:

  ClusterName:
    Type: String
    Default: ecommerce-eks-cluster
    Description: Name of the EKS Cluster

  PrivateSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 1

  PrivateSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Private Subnet 2

  PublicSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 1

  PublicSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet 2

  ClusterSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: EKS Control Plane Security Group


Resources:

  #################################################################
  # IAM Role for EKS Control Plane
  #################################################################
  EKSClusterRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${ClusterName}-ekscluster-role"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: eks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
        - arn:aws:iam::aws:policy/AmazonEKSVPCResourceController
      Tags:
        - Key: Name
          Value: !Sub "${ClusterName}-ekscluster-role"

  #################################################################
  # EKS Cluster (NO OIDC)
  #################################################################
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: !Ref ClusterName
      RoleArn: !GetAtt EKSClusterRole.Arn

      Version: "1.31"

      ResourcesVpcConfig:
        SubnetIds:
          - !Ref PrivateSubnet1
          - !Ref PrivateSubnet2
          - !Ref PublicSubnet1
          - !Ref PublicSubnet2

        SecurityGroupIds:
          - !Ref ClusterSecurityGroupId

        EndpointPrivateAccess: true
        EndpointPublicAccess: true

      Logging:
        ClusterLogging:
          EnabledTypes:
            - Type: api
            - Type: audit
            - Type: authenticator
            - Type: controllerManager
            - Type: scheduler


Outputs:

  EKSClusterName:
    Description: Name of the EKS Cluster
    Value: !Ref EKSCluster
    Export:
      Name: EKSClusterName

  EKSClusterArn:
    Description: ARN of the EKS Cluster
    Value: !GetAtt EKSCluster.Arn
    Export:
      Name: EKSClusterArn

  EKSClusterEndpoint:
    Description: API Endpoint of the EKS Cluster
    Value: !GetAtt EKSCluster.Endpoint
    Export:
      Name: EKSClusterEndpoint
