apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limits
  namespace: products
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limits
  namespace: orders
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limits
  namespace: inventory
spec:
  limits:
    - default:
        cpu: "500m"
        memory: "512Mi"
      defaultRequest:
        cpu: "250m"
        memory: "256Mi"
      type: Container
---
apiVersion: v1
kind: LimitRange
metadata:
  name: default-resource-limits
  namespace: frontend
spec:
  limits:
    - default:
        cpu: "300m"
        memory: "256Mi"
      defaultRequest:
        cpu: "150m"
        memory: "128Mi"
      type: Container
