apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: frontend
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: products-sa
  namespace: products
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: orders-sa
  namespace: orders
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: inventory-sa
  namespace: inventory
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: users-sa
  namespace: users
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-sa
  namespace: payments
