
# Developer Role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role-products
  namespace: products
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "delete"]  


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role-orders
  namespace: orders
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments", "configmaps"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "delete"]


---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer-role-inventory
  namespace: inventory
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments", "configmaps"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "delete"]

---
# Read-Only Roles 
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readonly-role-frontend
  namespace: frontend
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: readonly-role-database
  namespace: database
rules:
  - apiGroups: ["", "apps"]
    resources: ["pods", "services", "deployments"]
    verbs: ["get", "list", "watch"]
